--- #YAML:1.0
name:               Crypt-PKCS5
version:            0.01
abstract:           PKCS #5 v2.1: Password-Based Cryptography Standard.
author:
    - 小山浩之 <oyama@module.jp>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC_SHA1:  0
    Digest::MD5:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
